# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  folder_to_upload: dist/apps/dashboard
  blob_account: responsibleai
  blob_container: pullrequest
  blob_path: ${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref }}

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install yarn -g
      - name: Install packages
        run: yarn install
      - name: Check for code linter errors
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run tests
        run: yarn test